<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\src\结构型\Adapter\Adaptee.cs" Link="结构型\Adapter\Adaptee.cs" />
    <Compile Include="..\..\src\结构型\Adapter\ClassAdapter.cs" Link="结构型\Adapter\ClassAdapter.cs" />
    <Compile Include="..\..\src\结构型\Adapter\ObjectAdapter.cs" Link="结构型\Adapter\ObjectAdapter.cs" />
    <Compile Include="..\..\src\结构型\Bridge\Protocol\Dlt645Protocol.cs" Link="结构型\Bridge\Protocol\Dlt645Protocol.cs" />
    <Compile Include="..\..\src\结构型\Bridge\Protocol\ModbusRtuProtocol.cs" Link="结构型\Bridge\Protocol\ModbusRtuProtocol.cs" />
    <Compile Include="..\..\src\结构型\Bridge\Protocol\Protocol.cs" Link="结构型\Bridge\Protocol\Protocol.cs" />
    <Compile Include="..\..\src\结构型\Bridge\Transport\ITransport.cs" Link="结构型\Bridge\Transport\ITransport.cs" />
    <Compile Include="..\..\src\结构型\Bridge\Transport\SerialPortTransport.cs" Link="结构型\Bridge\Transport\SerialPortTransport.cs" />
    <Compile Include="..\..\src\结构型\Bridge\Transport\TcpTransport.cs" Link="结构型\Bridge\Transport\TcpTransport.cs" />
    <Compile Include="..\..\src\结构型\Composite\BranchNode.cs" Link="结构型\Composite\BranchNode.cs" />
    <Compile Include="..\..\src\结构型\Composite\LeafNode.cs" Link="结构型\Composite\LeafNode.cs" />
    <Compile Include="..\..\src\结构型\Composite\Node.cs" Link="结构型\Composite\Node.cs" />
    <Compile Include="..\..\src\结构型\Decorator\Decorator.cs" Link="结构型\Decorator\Decorator.cs" />
    <Compile Include="..\..\src\结构型\Decorator\DecoratorA.cs" Link="结构型\Decorator\DecoratorA.cs" />
    <Compile Include="..\..\src\结构型\Decorator\DecoratorB.cs" Link="结构型\Decorator\DecoratorB.cs" />
    <Compile Include="..\..\src\结构型\Decorator\IStable.cs" Link="结构型\Decorator\IStable.cs" />
    <Compile Include="..\..\src\结构型\Decorator\StableClass.cs" Link="结构型\Decorator\StableClass.cs" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="创建型\AbstractFactory\" />
    <Folder Include="创建型\Builder\" />
    <Folder Include="创建型\FactoryMethod\" />
    <Folder Include="创建型\Prototype\" />
    <Folder Include="创建型\Singleton\" />
    <Folder Include="结构型\Adapter\" />
    <Folder Include="结构型\Bridge\Protocol\" />
    <Folder Include="结构型\Bridge\Transport\" />
    <Folder Include="结构型\Composite\" />
    <Folder Include="结构型\Decorator\" />
    <Folder Include="结构型\Facade\" />
    <Folder Include="结构型\Flyweight\" />
    <Folder Include="结构型\Proxy\" />
    <Folder Include="行为型\ChainOfResponsibility\" />
    <Folder Include="行为型\Command\" />
    <Folder Include="行为型\Interpreter\" />
    <Folder Include="行为型\Iterator\" />
    <Folder Include="行为型\Mediator\" />
    <Folder Include="行为型\Memento\" />
    <Folder Include="行为型\Observer\" />
    <Folder Include="行为型\State\" />
    <Folder Include="行为型\Strategy\" />
    <Folder Include="行为型\TemplateMethod\" />
    <Folder Include="行为型\Visitor\" />
  </ItemGroup>

</Project>
